version: '3.1'

services:

  dbservice:
    image: mysql
    restart: always
    ports:
      - 8090:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: maravilla
    volumes:
      - ./mysqldb:/var/lib/mysqldb/data

  app:
    image: tp_dds_g1_2024
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - dbservice
