package modelo.elementos;

public enum Areas {
    CABALLITO,
    PALERMO,
    RECOLETA,
    BELGRANO,
    COLEGIALES,
    VILLA_CRESPO,
    VILLA_URQUIZA,
    VILLA_DEL_PARQUE,
    VILLA_LUGANO,
    VILLA_PUEYRREDON,
    VILLA_REAL,
    VILLA_SANTA_RITA,
    VILLA_SOLDATI,
    VILLA_ORTUZAR,
    VILLA_DEVOTO,
    VILLA_GRAL_MITRE,
    VILLA_LURO,
    VILLA_RIACHUELO,
    VILLA_SOCAYA,
}
